project 'BTCUSDChart.xcodeproj'

platform :ios, '9.0'

inhibit_all_warnings!

target 'BTCUSDChart' do

  use_frameworks!
  
  pod 'SocketRocket'
  pod 'Charts'
  pod 'ObjectMapper'
  pod 'SwiftyJSON'

  target 'BTCUSDChartTests' do
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'BTCUSDChart'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
    end
end
